INSERT INTO ROL (id, descripcion) VALUES (1, 'ADMINISTRADOR');
INSERT INTO ROL (id, descripcion) VALUES (2, 'USUARIO');

INSERT INTO USUARIO (ID, APELLIDOS, CORREO, NOMBRES, PASSWORD, USERNAME)
VALUES (1, 'PEREZ', 'jperez@test.com', 'JUAN', '1234', 'jperez');

INSERT INTO USUARIO (ID, APELLIDOS, CORREO, NOMBRES, PASSWORD, USERNAME)
VALUES (2, 'MATAMALA', 'smatamala@test.com', 'SERGIO', '1234', 'smatamala');

INSERT INTO USUARIO (ID, APELLIDOS, CORREO, NOMBRES, PASSWORD, USERNAME)
VALUES (3, 'SILVA', 'isilva@test.com', 'ISIDORA', '1234', 'isilva');

INSERT INTO USUARIO_ROL(ID, ROL_ID, USUARIO_ID)
VALUES (1, 1, 1);

INSERT INTO USUARIO_ROL(ID, ROL_ID, USUARIO_ID)
VALUES (2, 2, 2);

INSERT INTO USUARIO_ROL(ID, ROL_ID, USUARIO_ID)
VALUES (3, 2, 3);

INSERT INTO PRODUCTO(ID, COSTO, DESCRIPCION, NOMBRE)
VALUES (1, 29990, 'Taladro Bauker 6 velocidades', 'TALADRO BAUKER');

INSERT INTO PRODUCTO(ID, COSTO, DESCRIPCION, NOMBRE)
VALUES (2, 1990, 'Clavos del 4 color plata', 'CLAVOS');

INSERT INTO PRODUCTO(ID, COSTO, DESCRIPCION, NOMBRE)
VALUES (3, 29990, 'Codo tubería pvc 250mm', 'CODO PVC');

INSERT INTO SERVICIO(ID, COSTO, DESCRIPCION, NOMBRE, PROFESIONAL)
VALUES (1, 100, 'Clases de guitarra', 'GUITARRA', 'Bodoque');